// sampleLinkData.js

export const sampleLinks = [
  // --- Original 5 Links (with details added previously) ---
  {
    id: "link001",
    description: "Core1 to Site Alpha (Primary)",
    name: "Gig0/0/1-Alpha",
    ospfStatus: "Enabled",
    mplsStatus: "LDP",
    bandwidth: "10 Gbps",
    status: "up",
    type: "core-to-site",
    additionalDetails: {
      mediaType: "Fiber LR",
      cdpNeighbors: "SiteAlpha-Switch1 (port Gi0/1)",
      containerName: "N/A",
      mtu: "9000",
      crcErrors: "0",
      inputDataRate: "5.2 Gbps",
      outputDataRate: "3.1 Gbps",
      txPower: "-2.5 dBm",
      rxPower: "-2.8 dBm",
    },
  },
  {
    id: "link002",
    description: "Core1 to Site Beta (Backup)",
    name: "Gig0/0/2-Beta",
    ospfStatus: "Passive",
    mplsStatus: "Disabled",
    bandwidth: "1 Gbps",
    status: "down",
    type: "core-to-site",
    issueType: "Link physically down - No Light",
    additionalDetails: {
      mediaType: "Fiber SR",
      cdpNeighbors: "N/A (Link Down)",
      mtu: "1500",
      crcErrors: "N/A",
      inputDataRate: "0 Mbps",
      outputDataRate: "0 Mbps",
      txPower: "N/A",
      rxPower: "N/A",
    },
  },
  {
    id: "link003",
    description: "Core1 (SiteX) to Core2 (SiteY)",
    name: "Ten0/1/0-C2SY",
    ospfStatus: "Enabled",
    mplsStatus: "RSVP-TE",
    bandwidth: "40 Gbps",
    status: "up",
    type: "inter-core-different-site",
  },
  {
    id: "link004",
    description: "Core1 (SiteX) to Core3 (SiteX)",
    name: "Ten0/1/1-C3SX",
    ospfStatus: "Enabled",
    mplsStatus: "Segment Routing",
    bandwidth: "100 Gbps",
    status: "issue",
    type: "inter-core-same-site",
    issueType: "High CRC Count, Intermittent Flaps",
    additionalDetails: {
      mediaType: "Fiber ER",
      cdpNeighbors: "Core3-SiteX (Ten0/1/1)",
      containerName: "LAG-Bundle-10",
      mtu: "9216",
      crcErrors: "5012",
      inputDataRate: "70 Gbps",
      outputDataRate: "65 Gbps",
      txPower: "0.5 dBm",
      rxPower: "-15.0 dBm (Degraded)",
    },
  },
  {
    id: "link005",
    description: "Core1 to Site Gamma",
    name: "Gig0/0/3-Gamma",
    ospfStatus: "Enabled",
    mplsStatus: "LDP",
    bandwidth: "10 Gbps",
    status: "up",
    type: "core-to-site",
  },
  {
    id: "link006",
    description: "Interconnect to ISP-A",
    name: "HundredGigE0/2/0",
    ospfStatus: "N/A (BGP Peering)",
    mplsStatus: "N/A",
    bandwidth: "100 Gbps",
    status: "up",
    type: "inter-core-different-site",
    additionalDetails: {
      mediaType: "QSFP28-LR4",
      cdpNeighbors: "ISP-A-EdgeRouter (Hu0/0/0)",
      containerName: "N/A",
      mtu: "9000",
      crcErrors: "2",
      inputDataRate: "45.7 Gbps",
      outputDataRate: "50.3 Gbps",
      txPower: "-1.0 dBm",
      rxPower: "-1.2 dBm",
    },
  },
  {
    id: "link007",
    description: "Link to Management Network Switch",
    name: "mgmt0",
    ospfStatus: "Passive",
    mplsStatus: "Disabled",
    bandwidth: "1 Gbps",
    status: "up",
    type: "core-to-site",
  },
  {
    id: "link008",
    description: "Core2 (SiteY) to Site Delta",
    name: "Gig0/0/0-Delta",
    ospfStatus: "Enabled",
    mplsStatus: "LDP",
    bandwidth: "1 Gbps",
    status: "issue",
    type: "core-to-site",
    issueType: "Unstable - Rx Power Fluctuating",
    additionalDetails: {
      mediaType: "Copper SFP",
      cdpNeighbors: "SiteDelta-Router (Gi0/0)",
      mtu: "1500",
      crcErrors: "35",
      inputDataRate: "200 Mbps",
      outputDataRate: "150 Mbps",
      rxPower: "-7.0 dBm to -12.0 dBm",
    },
  },
  {
    id: "link009",
    description: "Core3 (SiteX) to Core1 (SiteX) - Redundant Path",
    name: "Ten0/1/2-C1SX",
    ospfStatus: "Enabled (High Cost)",
    mplsStatus: "Segment Routing",
    bandwidth: "100 Gbps",
    status: "up",
    type: "inter-core-same-site",
    additionalDetails: {
      mediaType: "Fiber ER",
      cdpNeighbors: "Core1-SiteX (Ten0/1/2)",
      containerName: "LAG-Bundle-10",
      mtu: "9216",
      crcErrors: "0",
    },
  },
  {
    id: "link010",
    description: "Connection to Voice Gateway",
    name: "FastEth0/3/0",
    ospfStatus: "Disabled",
    mplsStatus: "Disabled",
    bandwidth: "100 Mbps",
    status: "up",
    type: "core-to-site",
  },
  {
    id: "link011",
    description: "Site Epsilon Primary Link",
    name: "FortyGigE1/0/0",
    ospfStatus: "Enabled",
    mplsStatus: "LDP",
    bandwidth: "40 Gbps",
    status: "up",
    type: "core-to-site",
    additionalDetails: {
      mediaType: "QSFP+ SR4",
      inputDataRate: "22 Gbps",
      outputDataRate: "18 Gbps",
    },
  },
  {
    id: "link012",
    description: "Dark Fiber to DR Site",
    name: "WDM-Channel-3",
    ospfStatus: "Enabled",
    mplsStatus: "RSVP-TE (Protection Path)",
    bandwidth: "10 Gbps DWDM",
    status: "down",
    type: "inter-core-different-site",
    issueType: "Fiber Cut suspected (No Light)",
  },
  {
    id: "link013",
    description: "Temporary Test Loopback",
    name: "Loopback100",
    ospfStatus: "Passive",
    mplsStatus: "N/A",
    bandwidth: "N/A",
    status: "up",
    type: "core-to-site",
    additionalDetails: {
      mtu: "1500",
      inputDataRate: "0 Mbps",
      outputDataRate: "0 Mbps",
    },
  },
  {
    id: "link014",
    description: "Inter-fabric Link (Core Internal)",
    name: "Fabric0/0",
    ospfStatus: "Enabled (iBGP)",
    mplsStatus: "Segment Routing",
    bandwidth: "400 Gbps",
    status: "up",
    type: "inter-core-same-site",
    additionalDetails: {
      mediaType: "OSFP DR4",
      crcErrors: "0",
    },
  },
  {
    id: "link015",
    description: "Link to IoT Gateway Cluster",
    name: "Bundle-Ether1",
    ospfStatus: "Enabled",
    mplsStatus: "LDP",
    bandwidth: "2x10 Gbps",
    status: "issue",
    type: "core-to-site",
    issueType: "One member link down in LAG",
    additionalDetails: {
      mediaType: "LAG (2x Fiber LR)",
      containerName: "Bundle-Ether1",
      mtu: "9100",
      crcErrors: "5 (on active member)",
      inputDataRate: "8 Gbps",
      outputDataRate: "7.5 Gbps",
    },
  },
];
