export const data = [
  // ... (your data array remains the same)
  {
    phrase: "Travel insurance",
    synonyms: 4,
    frequency: 34,
    sentiment: -0.92,
    impact: -31.3,
  },
  {
    phrase: "Coupon code",
    synonyms: 2,
    frequency: 33,
    sentiment: -0.86,
    impact: -28.45,
  },
  {
    phrase: "Wait time",
    synonyms: 7,
    frequency: 35,
    sentiment: -0.75,
    impact: -26.34,
  },
  {
    phrase: "Credit card",
    synonyms: 2,
    frequency: 18,
    sentiment: -0.84,
    impact: -15.18,
  },
  {
    phrase: "Booking confirmation",
    synonyms: 3,
    frequency: 16,
    sentiment: -0.77,
    impact: -12.33,
  },
  {
    phrase: "Travel document",
    synonyms: 1,
    frequency: 11,
    sentiment: -1.0,
    impact: -11.0,
  },
  {
    phrase: "Tour operator",
    synonyms: 0,
    frequency: 19,
    sentiment: -0.53,
    impact: -10.06,
  },
  {
    phrase: "Cancellation insurance",
    synonyms: 0,
    frequency: 8,
    sentiment: -0.92,
    impact: -7.33,
  },
  {
    phrase: "Price change",
    synonyms: 0,
    frequency: 8,
    sentiment: -0.9,
    impact: -7.24,
  },
  {
    phrase: "Speak german",
    synonyms: 0,
    frequency: 10,
    sentiment: -0.53,
    impact: -5.33,
  },
  {
    phrase: "15 minute",
    synonyms: 0,
    frequency: 7,
    sentiment: -0.71,
    impact: -5.0,
  },
  { phrase: "Flight time", synonyms: 0, frequency: 9, sentiment: 0, impact: 0 },
  {
    phrase: "Personal contact",
    synonyms: 0,
    frequency: 5,
    sentiment: 0.07,
    impact: 0.33,
  },
  {
    phrase: "Book holiday",
    synonyms: 0,
    frequency: 11,
    sentiment: 0.14,
    impact: 1.5,
  },
];
